# Generated by Django 4.2.13 on 2024-06-09 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Found",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obj",
                    models.CharField(
                        help_text="Enter de object description", max_length=100
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True,
                        help_text="Enter the object serial number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cell_number",
                    models.CharField(help_text="Enter a contact number", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Enter a contact email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "obs",
                    models.TextField(
                        blank=True,
                        help_text="Enter a description/observation",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Please use the following format: <em>YYYY-MM-DD</em>.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obj",
                    models.CharField(
                        help_text="Enter de object description", max_length=100
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True,
                        help_text="Enter the object serial number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cell_number",
                    models.CharField(help_text="Enter a contact number", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Enter a contact email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "obs",
                    models.TextField(
                        blank=True,
                        help_text="Enter a description/observation",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Please use the following format: <em>YYYY-MM-DD</em>.",
                    ),
                ),
            ],
        ),
    ]
